apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"external-secrets.io/v1beta1","kind":"SecretStore","metadata":{"annotations":{},"name":"devops-dev","namespace":"devops-dev"},"spec":{"provider":{"vault":{"auth":{"kubernetes":{"mountPath":"kubernetes","role":"devops-dev","serviceAccountRef":{"name":"devops-dev-svcaccount"}}},"path":"secret","server":"http://vault.vault.svc.cluster.local:8200","version":"v2"}}}}
  creationTimestamp: '2024-12-21T05:22:21Z'
  generation: 2
  name: devops-dev
  namespace: devops-dev
  resourceVersion: '22551'
  uid: 628a63e0-0c71-4cb8-b35e-ba04553ca555
  selfLink: >-
    /apis/external-secrets.io/v1beta1/namespaces/devops-dev/secretstores/devops-dev
status:
  capabilities: ReadWrite
  conditions:
    - lastTransitionTime: '2024-12-21T05:22:33Z'
      message: unable to create client
      reason: InvalidProviderConfig
      status: 'False'
      type: Ready
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: devops-dev
          serviceAccountRef:
            name: devops-dev-svcaccount
      path: secret
      server: http://vault.vault.svc.cluster.local:8200
      version: v2
