apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-ITEM-tls
spec:
  secretName: ingress-ITEM-tls
  duration: 8760h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: ITEM.okestro.me
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - ITEM.okestro.me
    - ITEM.default.okestro-k8s.okestro.me
    - ITEM.NS.okestro-k8s.okestro.me
